Feature/movies-firebase
mcwiekala/CodersCamp2021.Project.2-Single-Page-Applications pull request #37
Opened 2022-02-04 19:44 UTC by judytabaca

2022-02-05 01:24 UTC, calidad-mk approved these changes

2022-02-05 15:18 UTC, mcwiekala commented on src/components/movie-viewer/MovieBrowser.jsx
> +  const apiUrl =
zmień bazę z Realtime Database na Cloud Firestore dane testowe możesz dodać w osobny skrypcie inicjalizacyjnym

2022-02-06 18:03 UTC, mcwiekala requested changes
A co z MovieDetails tam dane są brane omdb, to trzeba zmienić w tym tasku dane masz brać z firebase

2022-02-08 19:51 UTC, TRG-T approved these changes

2022-02-08 21:34 UTC, closed without merging